- name: Need to create the user
  hosts: localhost
  tasks:
  - name: check if the user exists
  # the below line is used to run linux command directly when ansible module is not available
    ansible.builtin.command: id roboshop # this is like how linux command will run in shellscript $() and store in variable and that variable had given under register
    register: USERID 
    ignore_errors: true
  
  - name: printing
    ansible.builtin.debug: 
      msg: The output is {{USERID}}
  - name: printing the exit status
    ansible.builtin.debug:
      msg: "{{USERID.rc}}"
  - name: creating roboshop user
    become: yes
    ansible.builtin.user:
      name: Roboshop
    when: USERID.rc !=0
