- name: install the packages
  hosts: Mongodb
  become: yes
  tasks:
  - name: Install the package
    ansible.builtin.yum:
    name: "{{item}}"
    state: installed

    loop:
    - nginx
    - postfix